### ISSUE TITLE
import statements missing?

### ISSUE THREAD

**Issue by danbri** [stephencwelch/Neural-Networks-Demystified#1]
I had to add an import for numpy as np, ... and now I see 'plot()' used without declaration. Am I missing something obvious? e.g. in pt2 plot(testInput, sigmoid(testInput), linewidth= 2)

**Comment by stephencwelch** [comment]
Thanks for bringing this up - it depends on how you launch the iPython notebook. I launch as: 

ipython notebook --pylab inline

The pylab command imports numpy and matplotlib and such. What do you think is a more appropriate fix: adding potentially redundant import statements to the notebooks, or adding instructions about how to launch the notebook?

Thanks!

**Comment by danbri** [comment]
Ah, I didn't realise :) so perhaps the latter... (mentioning the imports that this makes if you know). Looking at http://stackoverflow.com/questions/19410042/how-to-make-ipython-notebook-inline-matplotlib-graphics there seems to be some confusion in this area...

**Comment by stephencwelch** [comment]
Alrighty, I'll add a note to the README. Thank you!
