### ISSUE TITLE
where is predict function?

### ISSUE THREAD

**Issue by halilagin** [stephencwelch/Neural-Networks-Demystified#10]
Dear Stephen,

I learnt lots of things from your videos and pyhton codes. Thank you! However I could not find a predict function in your code. Is it missing? I think It would be nice to add this function.

Best,

Halil Agin.

**Comment by stephencwelch** [comment]
Great, thanks! The "forward" method takes care of prediction. Thanks!

**Comment by felipe-melo** [comment]
Dont worry it was my mistake
