### ISSUE TITLE
Regularization parameter typo?

### ISSUE THREAD

**Issue by Jayanth-Krishnan-Natarajan** [stephencwelch/Neural-Networks-Demystified#15]
Hey Stephen,
Thanks a LOT for this awesome series! :D I can't imagine the amount of time it must have taken to prepare all this content!

So, I think I noticed a typo in ln [20] of part 7 ( https://github.com/stephencwelch/Neural-Networks-Demystified/blob/master/Part%207%20Overfitting%2C%20Testing%2C%20and%20Regularization.ipynb )

```
delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
#Add gradient of regularization term:
dJdW2 = np.dot(self.a2.T, delta3)/X.shape[0] + self.lambd*self.W2

delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
#Add gradient of regularization term:
dJdW1 = np.dot(X.T, delta2)/X.shape[0] + self.lambd*self.W1
```

The regularization parameter is supposed to be **self.Lambda** but in the above snippet, you use **self.lambd** - I'm guessing this is a typo? 

Also, I noticed that video 7 does not have any mention of the **'/X.shape[0]'** term inside the costFunctionPrime function! (https://youtu.be/S4ZUwgesjS8?t=4m58s) Maybe you could add an annotation about this missing term there? BTW, in the video the regularization parameter is being referred to as **self.Lambda** 

Cheers!
Jayanth Krishnan

**Comment by stephencwelch** [comment]
Hi Jayanth, 

Thank you for these corrections! I've fixed the part 7 notebook. I've decided to leave the video alone for now - I do say "we need to normalize the other part of our cost function", which is what we're doing by dividing by /X.shape[0]. I did add a comment to the notebook though that will hopefully clarity: 

"#We don't want cost to increase with the number of examples, so normalize by dividing the error term by number of examples(X.shape[0])"

Thanks for your input!
