### ISSUE TITLE
I think I spotted an error in your excellent tutorial

### ISSUE THREAD

**Issue by menecken** [stephencwelch/Neural-Networks-Demystified#3]
Right after the line "We can now replace dyHat/dz3 with f prime of z 3." the formula shows an "dz3/dW3" on the left side which sould be a "dJ/dW2" in my oppinion.

Thank you again! Great work.

**Comment by stephencwelch** [comment]
HI Bernhard - thanks for pointing this out - are you referring to the video or the ipython notebook? If the video, at what time does this happen? 

Thank you!

Stephen

**Comment by naturegirl** [comment]
Hey @stephencwelch 

I might have come across the typo mentioned here. See PR.

Cheers and thanks for the great videos!

**Comment by jdelange** [comment]
Hi Stephen,
I think there is an error in the `costFunctionPrime` calculation write-up for `W` and `W2`. Where `delta3` is calculated with a Hadamard product, `delta 2` is not. I think it should be, the dimensions don't add-up. I came across your video's in search of answers to complete an example by Stanford [http://ufldl.stanford.edu/wiki/index.php/Neural_Network_Vectorization](url). I hope your examples will help me get it to work. Fortunately your naming is very similar to the example.

By the way, great videos! That must have been a lot of work. Well done!

Jan, Amsterdam (further exploring your code)

**Comment by stephencwelch** [comment]
Hi Jan, 

To clarify, you're referring to the equations in the write-up, and not the code? If so, I'm not quite sure I follow - is there a special way I should be showing Hadamard products as opposed to matrix products in my equations? 

Thanks! 

Stephen

**Comment by jdelange** [comment]
Hi Stephen,

 It is in the write-up with the code examples. For delta 3 you apply element-wise multiplication (np.multiply) which is correct, however for delta 2 you do not. That does not make sense and it should not compile as the dimensions are wrong.
[Write-up](https://github.com/stephencwelch/Neural-Networks-Demystified/blob/master/Part%204%20Backpropagation.ipynb)
Here is the code:

```
delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
dJdW2 = np.dot(self.a2.T, delta3)

delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
dJdW1 = np.dot(X.T, delta2)  

```

And here’s the theory (equations 2 and 3 at the lower end of the page):
[Theory](http://ufldl.stanford.edu/wiki/index.php/Backpropagation_Algorithml)

Always a Hadamard / element wise multiplication.

By the way with your examples and the examples of Ryan Harris I managed to create working code in C# including a bias.

Jan
