### ISSUE TITLE
costFunction in Lecture 7

### ISSUE THREAD

**Issue by menecken** [stephencwelch/Neural-Networks-Demystified#4]
Hey everybode,

if `J` in the cost function is calculated like given in lecture 7

```
 J = 0.5*sum((y-self.yHat)**2)/X.shape[0] + (self.Lambda/2)*(sum(self.W1**2)+sum(self.W2**2))
```

`J` ends up being a vector what causes in my believe the following error

```
File "C:\Program Files\Anaconda\lib\site-packages\scipy\optimize\linesearch.py", line 148, in scalar_search_wolfe1
alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
```

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The problem is solved by adding another `sum()` to the calculation of `J`

```
    J2 = 0.5*sum((y-self.yHat)**2)/X.shape[0] + (self.Lambda/2)*(sum(sum(self.W1**2))+sum(self.W2**2))
```

after that `J` is a scalar again.

Did you miss the `sum()` or did I miss something (and ended up doing something mathematically incorrent).

Best regards and thanks in advance!

**Comment by stephencwelch** [comment]
Hi Bernhard - great question. sum() is an overloaded method, so you may be using the wrong one. Have you imported numpy? If you're using the notebook, I recommend launching with:

ipython notebook --pylab inline

The pylab command imports numpy, which has it's own sum() method. Let me know if this helps!

best, 

Stephen

**Comment by JohnRobson** [comment]
I'm running the .py file. I imported "import numpy as np" and I has the same problem when call "_res = optimize.minimize"

"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

I tried with python 2 and 3.

**Comment by stephencwelch** [comment]
hmmm, the optimize method is part of the scipy package I believe. Has this been properly imported into your environment? Are you using the iPython notebook, python through the terminal, or something else?

**Comment by JohnRobson** [comment]
Stephen

Thank you for your reply. I'm trying to run this code:

https://gist.github.com/JohnRobson/c7fdef075eb86e882f73

$ python2 nn.py # or python 3

And this is the error:

https://gist.github.com/JohnRobson/f28d0459be834b6d5067

**Comment by stephencwelch** [comment]
Hmm, I'm sure exactly what it causing your error. I really wrote those scripts to be imported into iPython notebooks and run from there. I used python 2 in development. I would test the optimize minimize method and see if it's working properly. Or use the iPython notebook for testing, and slowly move your code to it's own script after you're sure it's working. Good luck!

**Comment by JohnRobson** [comment]
Thank you for your reply.

Even with $ ipython nn.py or Open the iPython Notebook and create a new notebook (python 2 or 3) won't work.

https://gist.github.com/JohnRobson/a880dc45f0bbe15298c4

I'm not sure, my versions are:

$ python2 --version
Python 2.7.10
$ python --version
Python 3.5.0
$ ipython2 --version
4.0.0
$ ipython --version
4.0.0

Maybe this part in your code won't work in the my python/iphyton version.

**Comment by stephencwelch** [comment]
How are you launching the notebook? It should be as:

ipython notebook --pylab inline

**Comment by JohnRobson** [comment]
My version throw this error:

$ ipython notebook --pylab inline
[E 13:18:40.107 NotebookApp] Support for specifying --pylab on the command line has been removed.
[E 13:18:40.107 NotebookApp] Please use `%pylab inline` or `%matplotlib inline` in the notebook itself.

**Comment by JohnRobson** [comment]
Good news, not works:

Populating the interactive namespace from numpy and matplotlib
Optimization terminated successfully.
         Current function value: 3157.753031
         Iterations: 116
         Function evaluations: 137
         Gradient evaluations: 137

I put "%pylab inline" in the first line.

Do you know how can I do this "%pylab inline" in the python script to run using Python?

**Comment by JohnRobson** [comment]
I figure out:

$ ipython --pylab=auto nn.py

works ;)

**Comment by stephencwelch** [comment]
Excellent!
