### ISSUE TITLE
I'm confused - the ipynb files are actually XML

### ISSUE THREAD

**Issue by johnmuir** [stephencwelch/Neural-Networks-Demystified#5]
I thought the .ipynb files should be in JSON format.

Or have I got your intention completely misunderstood?

**Comment by stephencwelch** [comment]
If you open up .ipynb files in a program like sublime text, you can see the underlying JSON - although it's not very exciting to look at - to run and edit iPython notebooks, you need to install iPython and open notebooks using the iPython browser. Check out the iPython notebook docs for more info. Good luck!

**Comment by johnmuir** [comment]
Hi,
I downloaded the files and then opened them with a plain text editor (gedit & jedit) and they contain XML data, not JSON data. 

I also tried to open them with iPython Notebook and it said they did not have the correct JSON format.

Please try yourself... 

I'm still confused...

But a very big THANK YOU for the excellent lectures on neural networks - really great.

John

**Comment by BogdanSorlea** [comment]
you must be high or unable to use a proper plain text editor. just open one of those files in vi...

**Comment by stephencwelch** [comment]
To properly view/edit iPython notebooks (.ipynb), you need to install the iPython notebook software. Please follow the instructions here: http://jupyter.readthedocs.org/en/latest/install.html. Good luck!

**Comment by johnmuir** [comment]
Have either of you actually downloaded the files and looked at them with a plain Jane editor - like vi?
